### ISSUE TITLE
Errors when using this blueprint for new application

### ISSUE THREAD

**Issue by Oreoz** [ember-cli/ember-octane-blueprint#96]
Just ran `npx ember-cli new octane-demo -b @ember/octane-app-blueprint` in order to try out Ember Octane, instead of a brand new app I got:

```
Error creating new application. Removing generated directory `./octane-demo`
error is not defined


Stack Trace and Error Report: /var/folders/7v/wvwydgbd68720zfn53d5xx8c0000gn/T/error.dump.f35238eddc
547ea42c2cf8d5de2333d6.log
```

Content of Stack Trace & Error Report

```
ENV Summary:

  TIME: Thu Apr 11 2019 09:47:57 GMT-0400 (GMT-04:00)
  TITLE: ember
  ARGV:
  - /usr/local/Cellar/node@10/10.14.1/bin/node
  - /Users/oreoz/.npm/_npx/3725/bin/ember
  - new
  - octane-demo
  - -b
  - @ember/octane-app-blueprint
  EXEC_PATH: /usr/local/Cellar/node@10/10.14.1/bin/node
  TMPDIR: /var/folders/7v/wvwydgbd68720zfn53d5xx8c0000gn/T
  SHELL: /bin/bash
  PATH:
  - /Users/oreoz/.npm/_npx/3725/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/share/dotnet
  - ~/.dotnet/tools
  PLATFORM: darwin x64
  FREEMEM: 15826841600
  TOTALMEM: 34359738368
  UPTIME: 1325
  LOADAVG: 2.91552734375,2.74365234375,2.48974609375
  CPUS:
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.14.0
  - cldr: 34.0
  - http_parser: 2.8.0
  - icu: 63.1
  - modules: 64
  - napi: 3
  - nghttp2: 1.34.0
  - node: 10.14.1
  - openssl: 1.1.0j
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.23.2
  - v8: 6.8.275.32-node.36
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: error is not defined
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: error is not defined
  - name: ReferenceError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: ReferenceError: error is not defined
    at got.then.catch.result (/private/var/folders/7v/wvwydgbd68720zfn53d5xx8c0000gn/T/ember-cli2019311-3725-t7z19i.yzr28/node_modules/octane-blueprint-utils/index.js:58:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)

=================================================================================
```

Not really sure if the problem is on my end or not, but I have no problem creating apps with the default blueprint.

**Comment by NullVoxPopuli** [comment]
it just worked for me. :-\

is this still broken for you?

**Comment by Oreoz** [comment]
Still broken on for me :/ So now I can assume it's most likely a problem on my end.

**Comment by NullVoxPopuli** [comment]
can you share information about your environment / ember-cli version / etc?

**Comment by Oreoz** [comment]
Some of it is already in the error report above, here's the output of `ember version --verbose`:

```sh
ember-cli: 3.9.0
http_parser: 2.8.0
node: 10.14.1
v8: 6.8.275.32-node.36
uv: 1.23.2
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 63.1
unicode: 11.0
cldr: 34.0
tz: 2018e
os: darwin x64
```

I'm running macOS High Sierra 10.13.6.

Would any other information be of any help? I'll gladly provide it.

**Comment by sheriffderek** [comment]
Just tested it with

macOS: 10.14.1
node: v11.11.0
npm: 6.7.0

and worked as expected.

**Comment by NullVoxPopuli** [comment]
@Oreoz what happens when you try a different node version?

**Comment by Oreoz** [comment]
Just tried with node v11.13.0 and no dice. 

I'm sitting behind a corporate proxy, if that's a valuable information, but I have no problems creating an Ember app w/o this blueprint. Was able to reproduce with a teammates laptop, so that might be it.

**Comment by rwjblue** [comment]
The specific error you are getting is due to a bug in the error handling code for determining latest versions of ember-source (https://github.com/ember-cli/ember-octane-blueprint/pull/97). Unfortunately, https://github.com/ember-cli/ember-octane-blueprint/pull/97 will not fix the underlying issue but it will at least let us _see_ the **actual** error that is happening so we can hopefully dig into it.

**Comment by NullVoxPopuli** [comment]
@Oreoz a new version of the blueprint has been published that contains an error reporting fix -- can you try again and see if you get a specific error?

**Comment by Oreoz** [comment]
After clearing my npm cache, `npx ember-cli new octane-demo -b @ember/octane-app-blueprint` still yields:

```
=================================================================================

ENV Summary:

  TIME: Fri Apr 12 2019 08:31:01 GMT-0400 (GMT-04:00)
  TITLE: ember
  ARGV:
  - /usr/local/Cellar/node/11.13.0/bin/node
  - /Users/oreoz/.npm/_npx/17079/bin/ember
  - new
  - octane-demo
  - -b
  - @ember/octane-app-blueprint
  EXEC_PATH: /usr/local/Cellar/node/11.13.0/bin/node
  TMPDIR: /var/folders/7v/wvwydgbd68720zfn53d5xx8c0000gn/T
  SHELL: /bin/bash
  PATH:
  - /Users/oreoz/.npm/_npx/17079/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/share/dotnet
  - ~/.dotnet/tools
  PLATFORM: darwin x64
  FREEMEM: 16018661376
  TOTALMEM: 34359738368
  UPTIME: 80579
  LOADAVG: 1.5703125,2.25927734375,2.525390625
  CPUS:
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - brotli: 1.0.7
  - cldr: 34.0
  - http_parser: 2.8.0
  - icu: 63.1
  - llhttp: 1.1.1
  - modules: 67
  - napi: 4
  - nghttp2: 1.34.0
  - node: 11.13.0
  - openssl: 1.1.1b
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.27.0
  - v8: 7.0.276.38-node.18
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: error is not defined
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: error is not defined
  - name: ReferenceError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: ReferenceError: error is not defined
    at got.then.catch.result (/private/var/folders/7v/wvwydgbd68720zfn53d5xx8c0000gn/T/ember-cli2019312-17079-1jax2ig.anoig/node_modules/octane-blueprint-utils/index.js:58:7)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)

=================================================================================

```

However, `ember new octane-demo -b @ember/octane-app-blueprint` yields:

```
=================================================================================

ENV Summary:

  TIME: Fri Apr 12 2019 08:27:16 GMT-0400 (GMT-04:00)
  TITLE: ember
  ARGV:
  - /usr/local/Cellar/node/11.13.0/bin/node
  - /usr/local/bin/ember
  - new
  - octane-demo
  - -b
  - @ember/octane-app-blueprint
  EXEC_PATH: /usr/local/Cellar/node/11.13.0/bin/node
  TMPDIR: /var/folders/7v/wvwydgbd68720zfn53d5xx8c0000gn/T
  SHELL: /bin/bash
  PATH:
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/share/dotnet
  - ~/.dotnet/tools
  PLATFORM: darwin x64
  FREEMEM: 16552128512
  TOTALMEM: 34359738368
  UPTIME: 80354
  LOADAVG: 3.47802734375,2.763671875,2.728515625
  CPUS:
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - brotli: 1.0.7
  - cldr: 34.0
  - http_parser: 2.8.0
  - icu: 63.1
  - llhttp: 1.1.1
  - modules: 67
  - napi: 4
  - nghttp2: 1.34.0
  - node: 11.13.0
  - openssl: 1.1.1b
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.27.0
  - v8: 7.0.276.38-node.18
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: UNABLE_TO_VERIFY_LEAF_SIGNATURE
  - codeFrame: [undefined]
  - errorMessage: unable to verify the first certificate
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: unable to verify the first certificate
  - name: RequestError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: RequestError: unable to verify the first certificate
    at ClientRequest.req.once.err (/private/var/folders/7v/wvwydgbd68720zfn53d5xx8c0000gn/T/ember-cli2019312-17025-1ylq1v2.9u1e/node_modules/got/index.js:182:22)
    at Object.onceWrapper (events.js:281:20)
    at ClientRequest.emit (events.js:193:13)
    at TLSSocket.socketErrorListener (_http_client.js:397:9)
    at TLSSocket.emit (events.js:193:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)

=================================================================================
```

Which clearly points to foul-play by my corporate proxy -- would it be possible that I a new proxy setting needs to be set somewhere in order to use this blueprint? I have it set pretty much everywhere, including as an environment variable. The classic `ember new ember-app` works like a charm!

**Comment by visoft** [comment]
I'm seeing the same thing on my MacBook:

```
=================================================================================

ENV Summary:

  TIME: Fri Apr 12 2019 14:53:46 GMT-0400 (Eastern Daylight Time)
  TITLE: ember
  ARGV:
  - /Users/dwhite/.nvm/versions/node/v11.3.0/bin/node
  - /Users/dwhite/.nvm/versions/node/v11.3.0/bin/ember
  - new
  - ember-octane
  - -b
  - @ember/octane-app-blueprint
  EXEC_PATH: /Users/dwhite/.nvm/versions/node/v11.3.0/bin/node
  TMPDIR: /var/folders/b9/v_sc8tn94bv4qrqy67481crw0000gn/T
  SHELL: /bin/zsh
  PATH:
  - /Users/dwhite/.rvm/gems/ruby-2.6.2/bin
  - /Users/dwhite/.rvm/gems/ruby-2.6.2@global/bin
  - /Users/dwhite/.rvm/rubies/ruby-2.6.2/bin
  - /Users/dwhite/.nvm/versions/node/v11.3.0/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /Applications/Postgres.app/Contents/Versions/latest/bin
  - /Users/dwhite/.rvm/bin
  - /Users/dwhite/dev
  PLATFORM: darwin x64
  FREEMEM: 362246144
  TOTALMEM: 17179869184
  UPTIME: 69698
  LOADAVG: 1.9736328125,1.46630859375,1.29541015625
  CPUS:
  - Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz - 2700
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - cldr: 34.0
  - http_parser: 2.8.0
  - icu: 63.1
  - modules: 67
  - napi: 3
  - nghttp2: 1.34.0
  - node: 11.3.0
  - openssl: 1.1.0j
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.23.2
  - v8: 7.0.276.38-node.11
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: error is not defined
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: error is not defined
  - name: ReferenceError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: ReferenceError: error is not defined
    at got.then.catch.result (/private/var/folders/b9/v_sc8tn94bv4qrqy67481crw0000gn/T/ember-cli2019312-12210-k24sl5.pex2/node_modules/octane-blueprint-utils/index.js:58:7)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

=================================================================================```

I'm not behind a proxy, but seeing the message `error is not defined`.

**Comment by NullVoxPopuli** [comment]
if anyone still gets `error is not defined` you'll need to clear your npm/yarn cache. the latest version of the blueprint should still error for your setup, but the error will be printed (hopefully) instead of being undefined

**Comment by NullVoxPopuli** [comment]
Closing due to inactivity, if anyone still has this problem, please open a new issue :)
